version: '3.8'

services:
  postgres:
    container_name: nodewit-pg
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart:
      always
